pub const GET_MATCH_IDS_BY_QUEUE: &str = "[
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598608\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598611\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598612\",
        \"ret_msg\": null
    }
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598613\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598615\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598616\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598620\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598621\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598622\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598623\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598624\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598625\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598626\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598627\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598628\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598629\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598630\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598632\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598633\",
        \"ret_msg\": null
    },
    {
        \"Active_Flag\": \"n\",
        \"Match\": \"956598634\",
        \"ret_msg\": null
    }
]";

pub const GET_MATCH_DETAILS: &str = "[
    {
        \"Account_Level\": 119,
        \"ActiveId1\": 8879,
        \"ActiveId2\": 7672,
        \"ActiveId3\": 0,
        \"ActiveId4\": 0,
        \"ActivePlayerId\": \"4203198\",
        \"Assists\": 11,
        \"Ban1\": \"Ao Kuang\",
        \"Ban10\": \"Kumbhakarna\",
        \"Ban10Id\": 1993,
        \"Ban1Id\": 2034,
        \"Ban2\": \"Merlin\",
        \"Ban2Id\": 3566,
        \"Ban3\": \"Arachne\",
        \"Ban3Id\": 1699,
        \"Ban4\": \"King Arthur\",
        \"Ban4Id\": 3565,
        \"Ban5\": \"Bakasura\",
        \"Ban5Id\": 1755,
        \"Ban6\": \"Ratatoskr\",
        \"Ban6Id\": 2063,
        \"Ban7\": \"Zeus\",
        \"Ban7Id\": 1672,
        \"Ban8\": \"Bacchus\",
        \"Ban8Id\": 1809,
        \"Ban9\": \"Erlang Shen\",
        \"Ban9Id\": 2138,
        \"Camps_Cleared\": 0,
        \"Conquest_Losses\": 9,
        \"Conquest_Points\": 31,
        \"Conquest_Tier\": 7,
        \"Conquest_Wins\": 4,
        \"Damage_Bot\": 141036,
        \"Damage_Done_In_Hand\": 3960,
        \"Damage_Done_Magical\": 173744,
        \"Damage_Done_Physical\": 0,
        \"Damage_Mitigated\": 7767,
        \"Damage_Player\": 32708,
        \"Damage_Taken\": 17867,
        \"Damage_Taken_Magical\": 6818,
        \"Damage_Taken_Physical\": 11049,
        \"Deaths\": 3,
        \"Distance_Traveled\": 701431,
        \"Duel_Losses\": 0,
        \"Duel_Points\": 0,
        \"Duel_Tier\": 0,
        \"Duel_Wins\": 0,
        \"Entry_Datetime\": \"8/5/2019 12:06:23 AM\",
        \"Final_Match_Level\": 20,
        \"First_Ban_Side\": \"Winner\",
        \"GodId\": 1881,
        \"Gold_Earned\": 20824,
        \"Gold_Per_Minute\": 620,
        \"Healing\": 0,
        \"Healing_Bot\": 0,
        \"Healing_Player_Self\": 3797,
        \"ItemId1\": 7600,
        \"ItemId2\": 15725,
        \"ItemId3\": 8551,
        \"ItemId4\": 8354,
        \"ItemId5\": 7784,
        \"ItemId6\": 7594,
        \"Item_Active_1\": \"Purification Beads\",
        \"Item_Active_2\": \"Aegis Amulet\",
        \"Item_Active_3\": \"\",
        \"Item_Active_4\": \"\",
        \"Item_Purch_1\": \"Rod of Tahuti\",
        \"Item_Purch_2\": \"Evolved Book of Thoth\",
        \"Item_Purch_3\": \"Bancroft's Talon\",
        \"Item_Purch_4\": \"Spear of the Magus\",
        \"Item_Purch_5\": \"Chronos' Pendant\",
        \"Item_Purch_6\": \"Gem of Isolation\",
        \"Joust_Losses\": 0,
        \"Joust_Points\": 0,
        \"Joust_Tier\": 0,
        \"Joust_Wins\": 0,
        \"Killing_Spree\": 6,
        \"Kills_Bot\": 257,
        \"Kills_Double\": 2,
        \"Kills_Fire_Giant\": 0,
        \"Kills_First_Blood\": 0,
        \"Kills_Gold_Fury\": 1,
        \"Kills_Penta\": 0,
        \"Kills_Phoenix\": 1,
        \"Kills_Player\": 17,
        \"Kills_Quadra\": 0,
        \"Kills_Siege_Juggernaut\": 0,
        \"Kills_Single\": 15,
        \"Kills_Triple\": 0,
        \"Kills_Wild_Juggernaut\": 0,
        \"Map_Game\": \"Season 6 Conquest\",
        \"Mastery_Level\": 63,
        \"Match\": 956598608,
        \"Match_Duration\": 0,
        \"MergedPlayers\": null,
        \"Minutes\": 33,
        \"Multi_kill_Max\": 2,
        \"Objective_Assists\": 11,
        \"PartyId\": 4209112,
        \"Rank_Stat_Conquest\": 1160.02771,
        \"Rank_Stat_Duel\": 0,
        \"Rank_Stat_Joust\": 1509.375,
        \"Reference_Name\": \"Poseidon\",
        \"Region\": \"EU\",
        \"Skin\": \"Freedom Overload\",
        \"SkinId\": 17229,
        \"Structure_Damage\": 4734,
        \"Surrendered\": 0,
        \"TaskForce\": 1,
        \"Team1Score\": 0,
        \"Team2Score\": 0,
        \"TeamId\": 227264,
        \"Team_Name\": \"Descendant\",
        \"Time_In_Match_Seconds\": 2014,
        \"Towers_Destroyed\": 2,
        \"Wards_Placed\": 13,
        \"Win_Status\": \"Winner\",
        \"Winning_TaskForce\": 1,
        \"hasReplay\": \"n\",
        \"hz_gamer_tag\": null,
        \"hz_player_name\": \"Iago1999\",
        \"match_queue_id\": 451,
        \"name\": \"Ranked: Conquest\",
        \"playerId\": \"4203198\",
        \"playerName\": \"[DêA]Iago1999\",
        \"playerPortalId\": \"1\",
        \"playerPortalUserId\": null,
        \"ret_msg\": null
    },
    {
        \"Account_Level\": 147,
        \"ActiveId1\": 8879,
        \"ActiveId2\": 7672,
        \"ActiveId3\": 0,
        \"ActiveId4\": 0,
        \"ActivePlayerId\": \"0\",
        \"Assists\": 19,
        \"Ban1\": \"Ao Kuang\",
        \"Ban10\": \"Kumbhakarna\",
        \"Ban10Id\": 1993,
        \"Ban1Id\": 2034,
        \"Ban2\": \"Merlin\",
        \"Ban2Id\": 3566,
        \"Ban3\": \"Arachne\",
        \"Ban3Id\": 1699,
        \"Ban4\": \"King Arthur\",
        \"Ban4Id\": 3565,
        \"Ban5\": \"Bakasura\",
        \"Ban5Id\": 1755,
        \"Ban6\": \"Ratatoskr\",
        \"Ban6Id\": 2063,
        \"Ban7\": \"Zeus\",
        \"Ban7Id\": 1672,
        \"Ban8\": \"Bacchus\",
        \"Ban8Id\": 1809,
        \"Ban9\": \"Erlang Shen\",
        \"Ban9Id\": 2138,
        \"Camps_Cleared\": 0,
        \"Conquest_Losses\": 22,
        \"Conquest_Points\": 47,
        \"Conquest_Tier\": 9,
        \"Conquest_Wins\": 24,
        \"Damage_Bot\": 99382,
        \"Damage_Done_In_Hand\": 15911,
        \"Damage_Done_Magical\": 0,
        \"Damage_Done_Physical\": 132979,
        \"Damage_Mitigated\": 10414,
        \"Damage_Player\": 33597,
        \"Damage_Taken\": 25452,
        \"Damage_Taken_Magical\": 9679,
        \"Damage_Taken_Physical\": 15773,
        \"Deaths\": 4,
        \"Distance_Traveled\": 611303,
        \"Duel_Losses\": 0,
        \"Duel_Points\": 0,
        \"Duel_Tier\": 7,
        \"Duel_Wins\": 0,
        \"Entry_Datetime\": \"8/5/2019 12:06:23 AM\",
        \"Final_Match_Level\": 20,
        \"First_Ban_Side\": \"Winner\",
        \"GodId\": 2107,
        \"Gold_Earned\": 18962,
        \"Gold_Per_Minute\": 564,
        \"Healing\": 0,
        \"Healing_Bot\": 0,
        \"Healing_Player_Self\": 8519,
        \"ItemId1\": 15767,
        \"ItemId2\": 7523,
        \"ItemId3\": 14846,
        \"ItemId4\": 10482,
        \"ItemId5\": 17090,
        \"ItemId6\": 9236,
        \"Item_Active_1\": \"Purification Beads\",
        \"Item_Active_2\": \"Aegis Amulet\",
        \"Item_Active_3\": \"\",
        \"Item_Active_4\": \"\",
        \"Item_Purch_1\": \"Transcendence\",
        \"Item_Purch_2\": \"Titan's Bane\",
        \"Item_Purch_3\": \"Toxic Blade\",
        \"Item_Purch_4\": \"Odysseus' Bow\",
        \"Item_Purch_5\": \"Asi\",
        \"Item_Purch_6\": \"Bloodforge\",
        \"Joust_Losses\": 0,
        \"Joust_Points\": 0,
        \"Joust_Tier\": 7,
        \"Joust_Wins\": 0,
        \"Killing_Spree\": 13,
        \"Kills_Bot\": 168,
        \"Kills_Double\": 3,
        \"Kills_Fire_Giant\": 1,
        \"Kills_First_Blood\": 1,
        \"Kills_Gold_Fury\": 1,
        \"Kills_Penta\": 0,
        \"Kills_Phoenix\": 1,
        \"Kills_Player\": 17,
        \"Kills_Quadra\": 0,
        \"Kills_Siege_Juggernaut\": 0,
        \"Kills_Single\": 14,
        \"Kills_Triple\": 0,
        \"Kills_Wild_Juggernaut\": 0,
        \"Map_Game\": \"Season 6 Conquest\",
        \"Mastery_Level\": 102,
        \"Match\": 956598608,
        \"Match_Duration\": 0,
        \"MergedPlayers\": null,
        \"Minutes\": 33,
        \"Multi_kill_Max\": 2,
        \"Objective_Assists\": 13,
        \"PartyId\": 4243896,
        \"Rank_Stat_Conquest\": 1220.834,
        \"Rank_Stat_Duel\": 1503.9696,
        \"Rank_Stat_Joust\": 1441.67664,
        \"Reference_Name\": \"Skadi\",
        \"Region\": \"EU\",
        \"Skin\": \"Such Cold\",
        \"SkinId\": 14087,
        \"Structure_Damage\": 8014,
        \"Surrendered\": 0,
        \"TaskForce\": 1,
        \"Team1Score\": 0,
        \"Team2Score\": 0,
        \"TeamId\": 0,
        \"Team_Name\": \"\",
        \"Time_In_Match_Seconds\": 2014,
        \"Towers_Destroyed\": 2,
        \"Wards_Placed\": 6,
        \"Win_Status\": \"Winner\",
        \"Winning_TaskForce\": 1,
        \"hasReplay\": \"n\",
        \"hz_gamer_tag\": null,
        \"hz_player_name\": \"AkumaDevil\",
        \"match_queue_id\": 451,
        \"name\": \"Ranked: Conquest\",
        \"playerId\": \"0\",
        \"playerName\": \"\",
        \"playerPortalId\": null,
        \"playerPortalUserId\": null,
        \"ret_msg\": null
    },
    {
        \"Account_Level\": 136,
        \"ActiveId1\": 14157,
        \"ActiveId2\": 8879,
        \"ActiveId3\": 0,
        \"ActiveId4\": 0,
        \"ActivePlayerId\": \"0\",
        \"Assists\": 18,
        \"Ban1\": \"Ao Kuang\",
        \"Ban10\": \"Kumbhakarna\",
        \"Ban10Id\": 1993,
        \"Ban1Id\": 2034,
        \"Ban2\": \"Merlin\",
        \"Ban2Id\": 3566,
        \"Ban3\": \"Arachne\",
        \"Ban3Id\": 1699,
        \"Ban4\": \"King Arthur\",
        \"Ban4Id\": 3565,
        \"Ban5\": \"Bakasura\",
        \"Ban5Id\": 1755,
        \"Ban6\": \"Ratatoskr\",
        \"Ban6Id\": 2063,
        \"Ban7\": \"Zeus\",
        \"Ban7Id\": 1672,
        \"Ban8\": \"Bacchus\",
        \"Ban8Id\": 1809,
        \"Ban9\": \"Erlang Shen\",
        \"Ban9Id\": 2138,
        \"Camps_Cleared\": 0,
        \"Conquest_Losses\": 30,
        \"Conquest_Points\": 27,
        \"Conquest_Tier\": 10,
        \"Conquest_Wins\": 27,
        \"Damage_Bot\": 123092,
        \"Damage_Done_In_Hand\": 3300,
        \"Damage_Done_Magical\": 97,
        \"Damage_Done_Physical\": 137856,
        \"Damage_Mitigated\": 26725,
        \"Damage_Player\": 14861,
        \"Damage_Taken\": 26363,
        \"Damage_Taken_Magical\": 7957,
        \"Damage_Taken_Physical\": 18406,
        \"Deaths\": 8,
        \"Distance_Traveled\": 569203,
        \"Duel_Losses\": 3,
        \"Duel_Points\": 0,
        \"Duel_Tier\": 5,
        \"Duel_Wins\": 0,
        \"Entry_Datetime\": \"8/5/2019 12:06:23 AM\",
        \"Final_Match_Level\": 20,
        \"First_Ban_Side\": \"Winner\",
        \"GodId\": 3543,
        \"Gold_Earned\": 18627,
        \"Gold_Per_Minute\": 554,
        \"Healing\": 0,
        \"Healing_Bot\": 0,
        \"Healing_Player_Self\": 4410,
        \"ItemId1\": 17355,
        \"ItemId2\": 7539,
        \"ItemId3\": 8547,
        \"ItemId4\": 17467,
        \"ItemId5\": 7829,
        \"ItemId6\": 11111,
        \"Item_Active_1\": \"Teleport Glyph Upgrade\",
        \"Item_Active_2\": \"Purification Beads\",
        \"Item_Active_3\": \"\",
        \"Item_Active_4\": \"\",
        \"Item_Purch_1\": \"Pridwen\",
        \"Item_Purch_2\": \"Soul Eater\",
        \"Item_Purch_3\": \"Transcendence\",
        \"Item_Purch_4\": \"Contagion\",
        \"Item_Purch_5\": \"Brawler's Beat Stick\",
        \"Item_Purch_6\": \"The Crusher\",
        \"Joust_Losses\": 0,
        \"Joust_Points\": 0,
        \"Joust_Tier\": 5,
        \"Joust_Wins\": 0,
        \"Killing_Spree\": 5,
        \"Kills_Bot\": 194,
        \"Kills_Double\": 1,
        \"Kills_Fire_Giant\": 0,
        \"Kills_First_Blood\": 0,
        \"Kills_Gold_Fury\": 0,
        \"Kills_Penta\": 0,
        \"Kills_Phoenix\": 1,
        \"Kills_Player\": 7,
        \"Kills_Quadra\": 0,
        \"Kills_Siege_Juggernaut\": 0,
        \"Kills_Single\": 5,
        \"Kills_Triple\": 1,
        \"Kills_Wild_Juggernaut\": 0,
        \"Map_Game\": \"Season 6 Conquest\",
        \"Mastery_Level\": 88,
        \"Match\": 956598608,
        \"Match_Duration\": 0,
        \"MergedPlayers\": null,
        \"Minutes\": 33,
        \"Multi_kill_Max\": 3,
        \"Objective_Assists\": 7,
        \"PartyId\": 4243896,
        \"Rank_Stat_Conquest\": 1259.72522,
        \"Rank_Stat_Duel\": 1012.69177,
        \"Rank_Stat_Joust\": 1285.19165,
        \"Reference_Name\": \"Pele\",
        \"Region\": \"EU\",
        \"Skin\": \"Darkblade\",
        \"SkinId\": 16639,
        \"Structure_Damage\": 2173,
        \"Surrendered\": 0,
        \"TaskForce\": 1,
        \"Team1Score\": 0,
        \"Team2Score\": 0,
        \"TeamId\": 642892,
        \"Team_Name\": \"Gods of Helm\",
        \"Time_In_Match_Seconds\": 2014,
        \"Towers_Destroyed\": 1,
        \"Wards_Placed\": 15,
        \"Win_Status\": \"Winner\",
        \"Winning_TaskForce\": 1,
        \"hasReplay\": \"n\",
        \"hz_gamer_tag\": null,
        \"hz_player_name\": \"IvyGhost\",
        \"match_queue_id\": 451,
        \"name\": \"Ranked: Conquest\",
        \"playerId\": \"0\",
        \"playerName\": \"\",
        \"playerPortalId\": null,
        \"playerPortalUserId\": null,
        \"ret_msg\": null
    },
    {
        \"Account_Level\": 122,
        \"ActiveId1\": 8879,
        \"ActiveId2\": 8844,
        \"ActiveId3\": 0,
        \"ActiveId4\": 0,
        \"ActivePlayerId\": \"11553763\",
        \"Assists\": 19,
        \"Ban1\": \"Ao Kuang\",
        \"Ban10\": \"Kumbhakarna\",
        \"Ban10Id\": 1993,
        \"Ban1Id\": 2034,
        \"Ban2\": \"Merlin\",
        \"Ban2Id\": 3566,
        \"Ban3\": \"Arachne\",
        \"Ban3Id\": 1699,
        \"Ban4\": \"King Arthur\",
        \"Ban4Id\": 3565,
        \"Ban5\": \"Bakasura\",
        \"Ban5Id\": 1755,
        \"Ban6\": \"Ratatoskr\",
        \"Ban6Id\": 2063,
        \"Ban7\": \"Zeus\",
        \"Ban7Id\": 1672,
        \"Ban8\": \"Bacchus\",
        \"Ban8Id\": 1809,
        \"Ban9\": \"Erlang Shen\",
        \"Ban9Id\": 2138,
        \"Camps_Cleared\": 0,
        \"Conquest_Losses\": 92,
        \"Conquest_Points\": 28,
        \"Conquest_Tier\": 10,
        \"Conquest_Wins\": 83,
        \"Damage_Bot\": 58962,
        \"Damage_Done_In_Hand\": 2650,
        \"Damage_Done_Magical\": 0,
        \"Damage_Done_Physical\": 73669,
        \"Damage_Mitigated\": 14776,
        \"Damage_Player\": 20320,
        \"Damage_Taken\": 30141,
        \"Damage_Taken_Magical\": 9818,
        \"Damage_Taken_Physical\": 19351,
        \"Deaths\": 8,
        \"Distance_Traveled\": 694822,
        \"Duel_Losses\": 0,
        \"Duel_Points\": 0,
        \"Duel_Tier\": 7,
        \"Duel_Wins\": 0,
        \"Entry_Datetime\": \"8/5/2019 12:06:23 AM\",
        \"Final_Match_Level\": 20,
        \"First_Ban_Side\": \"Winner\",
        \"GodId\": 2005,
        \"Gold_Earned\": 17678,
        \"Gold_Per_Minute\": 526,
        \"Healing\": 0,
        \"Healing_Bot\": 0,
        \"Healing_Player_Self\": 4019,
        \"ItemId1\": 17356,
        \"ItemId2\": 11111,
        \"ItemId3\": 9813,
        \"ItemId4\": 14096,
        \"ItemId5\": 7935,
        \"ItemId6\": 9405,
        \"Item_Active_1\": \"Purification Beads\",
        \"Item_Active_2\": \"Blink Rune\",
        \"Item_Active_3\": \"\",
        \"Item_Active_4\": \"\",
        \"Item_Purch_1\": \"Arondight\",
        \"Item_Purch_2\": \"The Crusher\",
        \"Item_Purch_3\": \"Short Sword\",
        \"Item_Purch_4\": \"Blackthorn Hammer\",
        \"Item_Purch_5\": \"Magi's Cloak\",
        \"Item_Purch_6\": \"Malice\",
        \"Joust_Losses\": 0,
        \"Joust_Points\": 0,
        \"Joust_Tier\": 0,
        \"Joust_Wins\": 0,
        \"Killing_Spree\": 3,
        \"Kills_Bot\": 107,
        \"Kills_Double\": 0,
        \"Kills_Fire_Giant\": 0,
        \"Kills_First_Blood\": 0,
        \"Kills_Gold_Fury\": 0,
        \"Kills_Penta\": 0,
        \"Kills_Phoenix\": 0,
        \"Kills_Player\": 13,
        \"Kills_Quadra\": 0,
        \"Kills_Siege_Juggernaut\": 0,
        \"Kills_Single\": 13,
        \"Kills_Triple\": 0,
        \"Kills_Wild_Juggernaut\": 0,
        \"Map_Game\": \"Season 6 Conquest\",
        \"Mastery_Level\": 55,
        \"Match\": 956598608,
        \"Match_Duration\": 0,
        \"MergedPlayers\": null,
        \"Minutes\": 33,
        \"Multi_kill_Max\": 1,
        \"Objective_Assists\": 3,
        \"PartyId\": 4186335,
        \"Rank_Stat_Conquest\": 1205.07886,
        \"Rank_Stat_Duel\": 1249.87671,
        \"Rank_Stat_Joust\": 1509.375,
        \"Reference_Name\": \"Serqet\",
        \"Region\": \"EU\",
        \"Skin\": \"Kitty Kaboom\",
        \"SkinId\": 16684,
        \"Structure_Damage\": 1121,
        \"Surrendered\": 0,
        \"TaskForce\": 1,
        \"Team1Score\": 0,
        \"Team2Score\": 0,
        \"TeamId\": 256190,
        \"Team_Name\": \"NoArchersito\",
        \"Time_In_Match_Seconds\": 2014,
        \"Towers_Destroyed\": 1,
        \"Wards_Placed\": 0,
        \"Win_Status\": \"Winner\",
        \"Winning_TaskForce\": 1,
        \"hasReplay\": \"n\",
        \"hz_gamer_tag\": null,
        \"hz_player_name\": \"arzcher\",
        \"match_queue_id\": 451,
        \"name\": \"Ranked: Conquest\",
        \"playerId\": \"11553763\",
        \"playerName\": \"[NoArz]arzcher\",
        \"playerPortalId\": \"1\",
        \"playerPortalUserId\": null,
        \"ret_msg\": null
    },
    {
        \"Account_Level\": 109,
        \"ActiveId1\": 9120,
        \"ActiveId2\": 14154,
        \"ActiveId3\": 0,
        \"ActiveId4\": 0,
        \"ActivePlayerId\": \"2941367\",
        \"Assists\": 37,
        \"Ban1\": \"Ao Kuang\",
        \"Ban10\": \"Kumbhakarna\",
        \"Ban10Id\": 1993,
        \"Ban1Id\": 2034,
        \"Ban2\": \"Merlin\",
        \"Ban2Id\": 3566,
        \"Ban3\": \"Arachne\",
        \"Ban3Id\": 1699,
        \"Ban4\": \"King Arthur\",
        \"Ban4Id\": 3565,
        \"Ban5\": \"Bakasura\",
        \"Ban5Id\": 1755,
        \"Ban6\": \"Ratatoskr\",
        \"Ban6Id\": 2063,
        \"Ban7\": \"Zeus\",
        \"Ban7Id\": 1672,
        \"Ban8\": \"Bacchus\",
        \"Ban8Id\": 1809,
        \"Ban9\": \"Erlang Shen\",
        \"Ban9Id\": 2138,
        \"Camps_Cleared\": 0,
        \"Conquest_Losses\": 10,
        \"Conquest_Points\": 10,
        \"Conquest_Tier\": 9,
        \"Conquest_Wins\": 9,
        \"Damage_Bot\": 37280,
        \"Damage_Done_In_Hand\": 1153,
        \"Damage_Done_Magical\": 50867,
        \"Damage_Done_Physical\": 0,
        \"Damage_Mitigated\": 45262,
        \"Damage_Player\": 13587,
        \"Damage_Taken\": 28212,
        \"Damage_Taken_Magical\": 7457,
        \"Damage_Taken_Physical\": 20755,
        \"Deaths\": 2,
        \"Distance_Traveled\": 606487,
        \"Duel_Losses\": 0,
        \"Duel_Points\": 0,
        \"Duel_Tier\": 7,
        \"Duel_Wins\": 0,
        \"Entry_Datetime\": \"8/5/2019 12:06:23 AM\",
        \"Final_Match_Level\": 20,
        \"First_Ban_Side\": \"Winner\",
        \"GodId\": 2269,
        \"Gold_Earned\": 17118,
        \"Gold_Per_Minute\": 509,
        \"Healing\": 0,
        \"Healing_Bot\": 0,
        \"Healing_Player_Self\": 3991,
        \"ItemId1\": 15646,
        \"ItemId2\": 15594,
        \"ItemId3\": 9634,
        \"ItemId4\": 7528,
        \"ItemId5\": 17355,
        \"ItemId6\": 9361,
        \"Item_Active_1\": \"Magic Shell\",
        \"Item_Active_2\": \"Aegis Amulet Upgrade\",
        \"Item_Active_3\": \"\",
        \"Item_Active_4\": \"\",
        \"Item_Purch_1\": \"Evolved Hide of the Urchin\",
        \"Item_Purch_2\": \"Evolved Gauntlet of Thebes\",
        \"Item_Purch_3\": \"Shoes of Focus\",
        \"Item_Purch_4\": \"Sovereignty\",
        \"Item_Purch_5\": \"Pridwen\",
        \"Item_Purch_6\": \"Spirit Robe\",
        \"Joust_Losses\": 0,
        \"Joust_Points\": 0,
        \"Joust_Tier\": 0,
        \"Joust_Wins\": 0,
        \"Killing_Spree\": 0,
        \"Kills_Bot\": 11,
        \"Kills_Double\": 0,
        \"Kills_Fire_Giant\": 0,
        \"Kills_First_Blood\": 0,
        \"Kills_Gold_Fury\": 0,
        \"Kills_Penta\": 0,
        \"Kills_Phoenix\": 0,
        \"Kills_Player\": 0,
        \"Kills_Quadra\": 0,
        \"Kills_Siege_Juggernaut\": 0,
        \"Kills_Single\": 0,
        \"Kills_Triple\": 0,
        \"Kills_Wild_Juggernaut\": 0,
        \"Map_Game\": \"Season 6 Conquest\",
        \"Mastery_Level\": 95,
        \"Match\": 956598608,
        \"Match_Duration\": 0,
        \"MergedPlayers\": null,
        \"Minutes\": 33,
        \"Multi_kill_Max\": 0,
        \"Objective_Assists\": 13,
        \"PartyId\": 4209112,
        \"Rank_Stat_Conquest\": 1388.28235,
        \"Rank_Stat_Duel\": 1440.54956,
        \"Rank_Stat_Joust\": 1509.375,
        \"Reference_Name\": \"Ganesha\",
        \"Region\": \"EU\",
        \"Skin\": \"Primal Shaman\",
        \"SkinId\": 14948,
        \"Structure_Damage\": 1501,
        \"Surrendered\": 0,
        \"TaskForce\": 1,
        \"Team1Score\": 0,
        \"Team2Score\": 0,
        \"TeamId\": 227264,
        \"Team_Name\": \"Descendant\",
        \"Time_In_Match_Seconds\": 2014,
        \"Towers_Destroyed\": 0,
        \"Wards_Placed\": 3,
        \"Win_Status\": \"Winner\",
        \"Winning_TaskForce\": 1,
        \"hasReplay\": \"n\",
        \"hz_gamer_tag\": null,
        \"hz_player_name\": \"Noblevader\",
        \"match_queue_id\": 451,
        \"name\": \"Ranked: Conquest\",
        \"playerId\": \"2941367\",
        \"playerName\": \"[DêA]Noblevader\",
        \"playerPortalId\": \"5\",
        \"playerPortalUserId\": \"76561198007834814\",
        \"ret_msg\": null
    },
    {
        \"Account_Level\": 99,
        \"ActiveId1\": 9041,
        \"ActiveId2\": 7672,
        \"ActiveId3\": 0,
        \"ActiveId4\": 0,
        \"ActivePlayerId\": \"13713744\",
        \"Assists\": 6,
        \"Ban1\": \"Ao Kuang\",
        \"Ban10\": \"Kumbhakarna\",
        \"Ban10Id\": 1993,
        \"Ban1Id\": 2034,
        \"Ban2\": \"Merlin\",
        \"Ban2Id\": 3566,
        \"Ban3\": \"Arachne\",
        \"Ban3Id\": 1699,
        \"Ban4\": \"King Arthur\",
        \"Ban4Id\": 3565,
        \"Ban5\": \"Bakasura\",
        \"Ban5Id\": 1755,
        \"Ban6\": \"Ratatoskr\",
        \"Ban6Id\": 2063,
        \"Ban7\": \"Zeus\",
        \"Ban7Id\": 1672,
        \"Ban8\": \"Bacchus\",
        \"Ban8Id\": 1809,
        \"Ban9\": \"Erlang Shen\",
        \"Ban9Id\": 2138,
        \"Camps_Cleared\": 0,
        \"Conquest_Losses\": 30,
        \"Conquest_Points\": 29,
        \"Conquest_Tier\": 10,
        \"Conquest_Wins\": 33,
        \"Damage_Bot\": 57265,
        \"Damage_Done_In_Hand\": 1144,
        \"Damage_Done_Magical\": 72288,
        \"Damage_Done_Physical\": 0,
        \"Damage_Mitigated\": 20127,
        \"Damage_Player\": 15023,
        \"Damage_Taken\": 28690,
        \"Damage_Taken_Magical\": 11345,
        \"Damage_Taken_Physical\": 17345,
        \"Deaths\": 9,
        \"Distance_Traveled\": 498277,
        \"Duel_Losses\": 0,
        \"Duel_Points\": 0,
        \"Duel_Tier\": 0,
        \"Duel_Wins\": 0,
        \"Entry_Datetime\": \"8/5/2019 12:06:23 AM\",
        \"Final_Match_Level\": 20,
        \"First_Ban_Side\": \"Winner\",
        \"GodId\": 1676,
        \"Gold_Earned\": 16308,
        \"Gold_Per_Minute\": 485,
        \"Healing\": 1086,
        \"Healing_Bot\": 1570,
        \"Healing_Player_Self\": 7440,
        \"ItemId1\": 7600,
        \"ItemId2\": 7525,
        \"ItemId3\": 9634,
        \"ItemId4\": 8551,
        \"ItemId5\": 17467,
        \"ItemId6\": 12670,
        \"Item_Active_1\": \"Meditation Cloak\",
        \"Item_Active_2\": \"Aegis Amulet\",
        \"Item_Active_3\": \"\",
        \"Item_Active_4\": \"\",
        \"Item_Purch_1\": \"Rod of Tahuti\",
        \"Item_Purch_2\": \"Obsidian Shard\",
        \"Item_Purch_3\": \"Shoes of Focus\",
        \"Item_Purch_4\": \"Bancroft's Talon\",
        \"Item_Purch_5\": \"Contagion\",
        \"Item_Purch_6\": \"Spear of Desolation\",
        \"Joust_Losses\": 0,
        \"Joust_Points\": 0,
        \"Joust_Tier\": 0,
        \"Joust_Wins\": 0,
        \"Killing_Spree\": 1,
        \"Kills_Bot\": 106,
        \"Kills_Double\": 0,
        \"Kills_Fire_Giant\": 0,
        \"Kills_First_Blood\": 0,
        \"Kills_Gold_Fury\": 0,
        \"Kills_Penta\": 0,
        \"Kills_Phoenix\": 0,
        \"Kills_Player\": 5,
        \"Kills_Quadra\": 0,
        \"Kills_Siege_Juggernaut\": 0,
        \"Kills_Single\": 5,
        \"Kills_Triple\": 0,
        \"Kills_Wild_Juggernaut\": 0,
        \"Map_Game\": \"Season 6 Conquest\",
        \"Mastery_Level\": 73,
        \"Match\": 956598608,
        \"Match_Duration\": 0,
        \"MergedPlayers\": null,
        \"Minutes\": 33,
        \"Multi_kill_Max\": 1,
        \"Objective_Assists\": 0,
        \"PartyId\": 4105429,
        \"Rank_Stat_Conquest\": 1223.57861,
        \"Rank_Stat_Duel\": 0,
        \"Rank_Stat_Joust\": 0,
        \"Reference_Name\": \"Hades\",
        \"Region\": \"EU\",
        \"Skin\": \"Hades\",
        \"SkinId\": 9306,
        \"Structure_Damage\": 0,
        \"Surrendered\": 0,
        \"TaskForce\": 2,
        \"Team1Score\": 0,
        \"Team2Score\": 0,
        \"TeamId\": 0,
        \"Team_Name\": \"\",
        \"Time_In_Match_Seconds\": 2014,
        \"Towers_Destroyed\": 0,
        \"Wards_Placed\": 0,
        \"Win_Status\": \"Loser\",
        \"Winning_TaskForce\": 1,
        \"hasReplay\": \"n\",
        \"hz_gamer_tag\": null,
        \"hz_player_name\": \"SΛSH\",
        \"match_queue_id\": 451,
        \"name\": \"Ranked: Conquest\",
        \"playerId\": \"13713744\",
        \"playerName\": \"SΛSH\",
        \"playerPortalId\": \"5\",
        \"playerPortalUserId\": \"76561198869851753\",
        \"ret_msg\": null
    },
    {
        \"Account_Level\": 31,
        \"ActiveId1\": 14146,
        \"ActiveId2\": 7672,
        \"ActiveId3\": 0,
        \"ActiveId4\": 0,
        \"ActivePlayerId\": \"11135167\",
        \"Assists\": 2,
        \"Ban1\": \"Ao Kuang\",
        \"Ban10\": \"Kumbhakarna\",
        \"Ban10Id\": 1993,
        \"Ban1Id\": 2034,
        \"Ban2\": \"Merlin\",
        \"Ban2Id\": 3566,
        \"Ban3\": \"Arachne\",
        \"Ban3Id\": 1699,
        \"Ban4\": \"King Arthur\",
        \"Ban4Id\": 3565,
        \"Ban5\": \"Bakasura\",
        \"Ban5Id\": 1755,
        \"Ban6\": \"Ratatoskr\",
        \"Ban6Id\": 2063,
        \"Ban7\": \"Zeus\",
        \"Ban7Id\": 1672,
        \"Ban8\": \"Bacchus\",
        \"Ban8Id\": 1809,
        \"Ban9\": \"Erlang Shen\",
        \"Ban9Id\": 2138,
        \"Camps_Cleared\": 0,
        \"Conquest_Losses\": 2,
        \"Conquest_Points\": 0,
        \"Conquest_Tier\": 3,
        \"Conquest_Wins\": 0,
        \"Damage_Bot\": 83985,
        \"Damage_Done_In_Hand\": 10044,
        \"Damage_Done_Magical\": 0,
        \"Damage_Done_Physical\": 100328,
        \"Damage_Mitigated\": 7080,
        \"Damage_Player\": 16343,
        \"Damage_Taken\": 26681,
        \"Damage_Taken_Magical\": 7678,
        \"Damage_Taken_Physical\": 18253,
        \"Deaths\": 14,
        \"Distance_Traveled\": 509930,
        \"Duel_Losses\": 0,
        \"Duel_Points\": 0,
        \"Duel_Tier\": 0,
        \"Duel_Wins\": 0,
        \"Entry_Datetime\": \"8/5/2019 12:06:23 AM\",
        \"Final_Match_Level\": 20,
        \"First_Ban_Side\": \"Winner\",
        \"GodId\": 2179,
        \"Gold_Earned\": 15862,
        \"Gold_Per_Minute\": 472,
        \"Healing\": 0,
        \"Healing_Bot\": 0,
        \"Healing_Player_Self\": 4512,
        \"ItemId1\": 10482,
        \"ItemId2\": 17090,
        \"ItemId3\": 9626,
        \"ItemId4\": 7523,
        \"ItemId5\": 12674,
        \"ItemId6\": 7545,
        \"Item_Active_1\": \"Purification Beads Upgrade\",
        \"Item_Active_2\": \"Aegis Amulet\",
        \"Item_Active_3\": \"\",
        \"Item_Active_4\": \"\",
        \"Item_Purch_1\": \"Odysseus' Bow\",
        \"Item_Purch_2\": \"Asi\",
        \"Item_Purch_3\": \"Warrior Tabi\",
        \"Item_Purch_4\": \"Titan's Bane\",
        \"Item_Purch_5\": \"Wind Demon\",
        \"Item_Purch_6\": \"Deathbringer\",
        \"Joust_Losses\": 3,
        \"Joust_Points\": 0,
        \"Joust_Tier\": 3,
        \"Joust_Wins\": 0,
        \"Killing_Spree\": 2,
        \"Kills_Bot\": 136,
        \"Kills_Double\": 2,
        \"Kills_Fire_Giant\": 0,
        \"Kills_First_Blood\": 0,
        \"Kills_Gold_Fury\": 0,
        \"Kills_Penta\": 0,
        \"Kills_Phoenix\": 0,
        \"Kills_Player\": 8,
        \"Kills_Quadra\": 0,
        \"Kills_Siege_Juggernaut\": 0,
        \"Kills_Single\": 6,
        \"Kills_Triple\": 0,
        \"Kills_Wild_Juggernaut\": 0,
        \"Map_Game\": \"Season 6 Conquest\",
        \"Mastery_Level\": 7,
        \"Match\": 956598608,
        \"Match_Duration\": 0,
        \"MergedPlayers\": null,
        \"Minutes\": 33,
        \"Multi_kill_Max\": 2,
        \"Objective_Assists\": 1,
        \"PartyId\": 4261592,
        \"Rank_Stat_Conquest\": 1064.61877,
        \"Rank_Stat_Duel\": 1453.125,
        \"Rank_Stat_Joust\": 967.229431,
        \"Reference_Name\": \"Izanami\",
        \"Region\": \"EU\",
        \"Skin\": \"Izanami\",
        \"SkinId\": 13299,
        \"Structure_Damage\": 2680,
        \"Surrendered\": 0,
        \"TaskForce\": 2,
        \"Team1Score\": 0,
        \"Team2Score\": 0,
        \"TeamId\": 992066,
        \"Team_Name\": \"VikingBeard\",
        \"Time_In_Match_Seconds\": 2014,
        \"Towers_Destroyed\": 1,
        \"Wards_Placed\": 0,
        \"Win_Status\": \"Loser\",
        \"Winning_TaskForce\": 1,
        \"hasReplay\": \"n\",
        \"hz_gamer_tag\": null,
        \"hz_player_name\": \"Lolick22\",
        \"match_queue_id\": 451,
        \"name\": \"Ranked: Conquest\",
        \"playerId\": \"11135167\",
        \"playerName\": \"[All4O]Lolick22\",
        \"playerPortalId\": \"5\",
        \"playerPortalUserId\": \"76561198144697851\",
        \"ret_msg\": null
    },
    {
        \"Account_Level\": 109,
        \"ActiveId1\": 14157,
        \"ActiveId2\": 8844,
        \"ActiveId3\": 0,
        \"ActiveId4\": 0,
        \"ActivePlayerId\": \"0\",
        \"Assists\": 10,
        \"Ban1\": \"Ao Kuang\",
        \"Ban10\": \"Kumbhakarna\",
        \"Ban10Id\": 1993,
        \"Ban1Id\": 2034,
        \"Ban2\": \"Merlin\",
        \"Ban2Id\": 3566,
        \"Ban3\": \"Arachne\",
        \"Ban3Id\": 1699,
        \"Ban4\": \"King Arthur\",
        \"Ban4Id\": 3565,
        \"Ban5\": \"Bakasura\",
        \"Ban5Id\": 1755,
        \"Ban6\": \"Ratatoskr\",
        \"Ban6Id\": 2063,
        \"Ban7\": \"Zeus\",
        \"Ban7Id\": 1672,
        \"Ban8\": \"Bacchus\",
        \"Ban8Id\": 1809,
        \"Ban9\": \"Erlang Shen\",
        \"Ban9Id\": 2138,
        \"Camps_Cleared\": 0,
        \"Conquest_Losses\": 51,
        \"Conquest_Points\": 20,
        \"Conquest_Tier\": 10,
        \"Conquest_Wins\": 44,
        \"Damage_Bot\": 82712,
        \"Damage_Done_In_Hand\": 885,
        \"Damage_Done_Magical\": 4542,
        \"Damage_Done_Physical\": 94146,
        \"Damage_Mitigated\": 55333,
        \"Damage_Player\": 15976,
        \"Damage_Taken\": 35638,
        \"Damage_Taken_Magical\": 9491,
        \"Damage_Taken_Physical\": 24536,
        \"Deaths\": 8,
        \"Distance_Traveled\": 553138,
        \"Duel_Losses\": 1,
        \"Duel_Points\": 0,
        \"Duel_Tier\": 3,
        \"Duel_Wins\": 0,
        \"Entry_Datetime\": \"8/5/2019 12:06:23 AM\",
        \"Final_Match_Level\": 20,
        \"First_Ban_Side\": \"Winner\",
        \"GodId\": 1924,
        \"Gold_Earned\": 15532,
        \"Gold_Per_Minute\": 462,
        \"Healing\": 0,
        \"Healing_Bot\": 0,
        \"Healing_Player_Self\": 9375,
        \"ItemId1\": 7537,
        \"ItemId2\": 14085,
        \"ItemId3\": 9626,
        \"ItemId4\": 7641,
        \"ItemId5\": 9364,
        \"ItemId6\": 9111,
        \"Item_Active_1\": \"Teleport Glyph Upgrade\",
        \"Item_Active_2\": \"Blink Rune\",
        \"Item_Active_3\": \"\",
        \"Item_Active_4\": \"\",
        \"Item_Purch_1\": \"Mystical Mail\",
        \"Item_Purch_2\": \"Gladiator's Shield\",
        \"Item_Purch_3\": \"Warrior Tabi\",
        \"Item_Purch_4\": \"Breastplate of Valor\",
        \"Item_Purch_5\": \"Pestilence\",
        \"Item_Purch_6\": \"Runic Shield\",
        \"Joust_Losses\": 0,
        \"Joust_Points\": 0,
        \"Joust_Tier\": 7,
        \"Joust_Wins\": 0,
        \"Killing_Spree\": 3,
        \"Kills_Bot\": 152,
        \"Kills_Double\": 1,
        \"Kills_Fire_Giant\": 0,
        \"Kills_First_Blood\": 0,
        \"Kills_Gold_Fury\": 0,
        \"Kills_Penta\": 0,
        \"Kills_Phoenix\": 0,
        \"Kills_Player\": 6,
        \"Kills_Quadra\": 0,
        \"Kills_Siege_Juggernaut\": 0,
        \"Kills_Single\": 5,
        \"Kills_Triple\": 0,
        \"Kills_Wild_Juggernaut\": 0,
        \"Map_Game\": \"Season 6 Conquest\",
        \"Mastery_Level\": 99,
        \"Match\": 956598608,
        \"Match_Duration\": 0,
        \"MergedPlayers\": null,
        \"Minutes\": 33,
        \"Multi_kill_Max\": 2,
        \"Objective_Assists\": 1,
        \"PartyId\": 4174442,
        \"Rank_Stat_Conquest\": 1212.91956,
        \"Rank_Stat_Duel\": 1350.4126,
        \"Rank_Stat_Joust\": 1557.05,
        \"Reference_Name\": \"Tyr\",
        \"Region\": \"EU\",
        \"Skin\": \"PrivaTyr\",
        \"SkinId\": 9940,
        \"Structure_Damage\": 430,
        \"Surrendered\": 0,
        \"TaskForce\": 2,
        \"Team1Score\": 0,
        \"Team2Score\": 0,
        \"TeamId\": 700309433,
        \"Team_Name\": \"l D l Rebels\",
        \"Time_In_Match_Seconds\": 2014,
        \"Towers_Destroyed\": 0,
        \"Wards_Placed\": 4,
        \"Win_Status\": \"Loser\",
        \"Winning_TaskForce\": 1,
        \"hasReplay\": \"n\",
        \"hz_gamer_tag\": null,
        \"hz_player_name\": \"drteys\",
        \"match_queue_id\": 451,
        \"name\": \"Ranked: Conquest\",
        \"playerId\": \"0\",
        \"playerName\": \"\",
        \"playerPortalId\": null,
        \"playerPortalUserId\": null,
        \"ret_msg\": null
    },
    {
        \"Account_Level\": 89,
        \"ActiveId1\": 8844,
        \"ActiveId2\": 7672,
        \"ActiveId3\": 0,
        \"ActiveId4\": 0,
        \"ActivePlayerId\": \"13713856\",
        \"Assists\": 6,
        \"Ban1\": \"Ao Kuang\",
        \"Ban10\": \"Kumbhakarna\",
        \"Ban10Id\": 1993,
        \"Ban1Id\": 2034,
        \"Ban2\": \"Merlin\",
        \"Ban2Id\": 3566,
        \"Ban3\": \"Arachne\",
        \"Ban3Id\": 1699,
        \"Ban4\": \"King Arthur\",
        \"Ban4Id\": 3565,
        \"Ban5\": \"Bakasura\",
        \"Ban5Id\": 1755,
        \"Ban6\": \"Ratatoskr\",
        \"Ban6Id\": 2063,
        \"Ban7\": \"Zeus\",
        \"Ban7Id\": 1672,
        \"Ban8\": \"Bacchus\",
        \"Ban8Id\": 1809,
        \"Ban9\": \"Erlang Shen\",
        \"Ban9Id\": 2138,
        \"Camps_Cleared\": 0,
        \"Conquest_Losses\": 41,
        \"Conquest_Points\": 20,
        \"Conquest_Tier\": 7,
        \"Conquest_Wins\": 36,
        \"Damage_Bot\": 100479,
        \"Damage_Done_In_Hand\": 3015,
        \"Damage_Done_Magical\": 0,
        \"Damage_Done_Physical\": 115234,
        \"Damage_Mitigated\": 10655,
        \"Damage_Player\": 14755,
        \"Damage_Taken\": 27901,
        \"Damage_Taken_Magical\": 8540,
        \"Damage_Taken_Physical\": 18429,
        \"Deaths\": 13,
        \"Distance_Traveled\": 503760,
        \"Duel_Losses\": 0,
        \"Duel_Points\": 0,
        \"Duel_Tier\": 0,
        \"Duel_Wins\": 0,
        \"Entry_Datetime\": \"8/5/2019 12:06:23 AM\",
        \"Final_Match_Level\": 20,
        \"First_Ban_Side\": \"Winner\",
        \"GodId\": 2270,
        \"Gold_Earned\": 14736,
        \"Gold_Per_Minute\": 439,
        \"Healing\": 0,
        \"Healing_Bot\": 0,
        \"Healing_Player_Self\": 3470,
        \"ItemId1\": 9836,
        \"ItemId2\": 7904,
        \"ItemId3\": 9626,
        \"ItemId4\": 12680,
        \"ItemId5\": 8550,
        \"ItemId6\": 9826,
        \"Item_Active_1\": \"Blink Rune\",
        \"Item_Active_2\": \"Aegis Amulet\",
        \"Item_Active_3\": \"\",
        \"Item_Active_4\": \"\",
        \"Item_Purch_1\": \"Void Shield\",
        \"Item_Purch_2\": \"Jotunn's Wrath\",
        \"Item_Purch_3\": \"Warrior Tabi\",
        \"Item_Purch_4\": \"Heartseeker\",
        \"Item_Purch_5\": \"Hydra's Lament\",
        \"Item_Purch_6\": \"Cursed Gauntlet\",
        \"Joust_Losses\": 0,
        \"Joust_Points\": 0,
        \"Joust_Tier\": 0,
        \"Joust_Wins\": 0,
        \"Killing_Spree\": 1,
        \"Kills_Bot\": 168,
        \"Kills_Double\": 0,
        \"Kills_Fire_Giant\": 0,
        \"Kills_First_Blood\": 0,
        \"Kills_Gold_Fury\": 0,
        \"Kills_Penta\": 0,
        \"Kills_Phoenix\": 0,
        \"Kills_Player\": 2,
        \"Kills_Quadra\": 0,
        \"Kills_Siege_Juggernaut\": 0,
        \"Kills_Single\": 2,
        \"Kills_Triple\": 0,
        \"Kills_Wild_Juggernaut\": 0,
        \"Map_Game\": \"Season 6 Conquest\",
        \"Mastery_Level\": 69,
        \"Match\": 956598608,
        \"Match_Duration\": 0,
        \"MergedPlayers\": null,
        \"Minutes\": 33,
        \"Multi_kill_Max\": 1,
        \"Objective_Assists\": 1,
        \"PartyId\": 4105429,
        \"Rank_Stat_Conquest\": 957.0455,
        \"Rank_Stat_Duel\": 0,
        \"Rank_Stat_Joust\": 1300.77246,
        \"Reference_Name\": \"Da Ji\",
        \"Region\": \"EU\",
        \"Skin\": \"Data Dealer\",
        \"SkinId\": 17227,
        \"Structure_Damage\": 1157,
        \"Surrendered\": 0,
        \"TaskForce\": 2,
        \"Team1Score\": 0,
        \"Team2Score\": 0,
        \"TeamId\": 0,
        \"Team_Name\": \"\",
        \"Time_In_Match_Seconds\": 2014,
        \"Towers_Destroyed\": 1,
        \"Wards_Placed\": 0,
        \"Win_Status\": \"Loser\",
        \"Winning_TaskForce\": 1,
        \"hasReplay\": \"n\",
        \"hz_gamer_tag\": null,
        \"hz_player_name\": \"JALFIA\",
        \"match_queue_id\": 451,
        \"name\": \"Ranked: Conquest\",
        \"playerId\": \"13713856\",
        \"playerName\": \"JALFIA\",
        \"playerPortalId\": \"5\",
        \"playerPortalUserId\": \"76561198889796352\",
        \"ret_msg\": null
    },
    {
        \"Account_Level\": 143,
        \"ActiveId1\": 7353,
        \"ActiveId2\": 7672,
        \"ActiveId3\": 0,
        \"ActiveId4\": 0,
        \"ActivePlayerId\": \"4353122\",
        \"Assists\": 9,
        \"Ban1\": \"Ao Kuang\",
        \"Ban10\": \"Kumbhakarna\",
        \"Ban10Id\": 1993,
        \"Ban1Id\": 2034,
        \"Ban2\": \"Merlin\",
        \"Ban2Id\": 3566,
        \"Ban3\": \"Arachne\",
        \"Ban3Id\": 1699,
        \"Ban4\": \"King Arthur\",
        \"Ban4Id\": 3565,
        \"Ban5\": \"Bakasura\",
        \"Ban5Id\": 1755,
        \"Ban6\": \"Ratatoskr\",
        \"Ban6Id\": 2063,
        \"Ban7\": \"Zeus\",
        \"Ban7Id\": 1672,
        \"Ban8\": \"Bacchus\",
        \"Ban8Id\": 1809,
        \"Ban9\": \"Erlang Shen\",
        \"Ban9Id\": 2138,
        \"Camps_Cleared\": 0,
        \"Conquest_Losses\": 29,
        \"Conquest_Points\": 70,
        \"Conquest_Tier\": 9,
        \"Conquest_Wins\": 23,
        \"Damage_Bot\": 63530,
        \"Damage_Done_In_Hand\": 2659,
        \"Damage_Done_Magical\": 85922,
        \"Damage_Done_Physical\": 0,
        \"Damage_Mitigated\": 4942,
        \"Damage_Player\": 22392,
        \"Damage_Taken\": 22386,
        \"Damage_Taken_Magical\": 11110,
        \"Damage_Taken_Physical\": 10035,
        \"Deaths\": 10,
        \"Distance_Traveled\": 543961,
        \"Duel_Losses\": 2,
        \"Duel_Points\": 26,
        \"Duel_Tier\": 7,
        \"Duel_Wins\": 1,
        \"Entry_Datetime\": \"8/5/2019 12:06:23 AM\",
        \"Final_Match_Level\": 19,
        \"First_Ban_Side\": \"Winner\",
        \"GodId\": 1958,
        \"Gold_Earned\": 13564,
        \"Gold_Per_Minute\": 404,
        \"Healing\": 0,
        \"Healing_Bot\": 0,
        \"Healing_Player_Self\": 510,
        \"ItemId1\": 15483,
        \"ItemId2\": 7784,
        \"ItemId3\": 9633,
        \"ItemId4\": 7594,
        \"ItemId5\": 12670,
        \"ItemId6\": 9859,
        \"Item_Active_1\": \"Heavenly Wings\",
        \"Item_Active_2\": \"Aegis Amulet\",
        \"Item_Active_3\": \"\",
        \"Item_Active_4\": \"\",
        \"Item_Purch_1\": \"Evolved Mage's Blessing\",
        \"Item_Purch_2\": \"Chronos' Pendant\",
        \"Item_Purch_3\": \"Shoes of the Magi\",
        \"Item_Purch_4\": \"Gem of Isolation\",
        \"Item_Purch_5\": \"Spear of Desolation\",
        \"Item_Purch_6\": \"Book of Souls\",
        \"Joust_Losses\": 0,
        \"Joust_Points\": 0,
        \"Joust_Tier\": 5,
        \"Joust_Wins\": 0,
        \"Killing_Spree\": 1,
        \"Kills_Bot\": 107,
        \"Kills_Double\": 0,
        \"Kills_Fire_Giant\": 0,
        \"Kills_First_Blood\": 0,
        \"Kills_Gold_Fury\": 0,
        \"Kills_Penta\": 0,
        \"Kills_Phoenix\": 0,
        \"Kills_Player\": 2,
        \"Kills_Quadra\": 0,
        \"Kills_Siege_Juggernaut\": 0,
        \"Kills_Single\": 2,
        \"Kills_Triple\": 0,
        \"Kills_Wild_Juggernaut\": 0,
        \"Map_Game\": \"Season 6 Conquest\",
        \"Mastery_Level\": 82,
        \"Match\": 956598608,
        \"Match_Duration\": 0,
        \"MergedPlayers\": null,
        \"Minutes\": 33,
        \"Multi_kill_Max\": 1,
        \"Objective_Assists\": 0,
        \"PartyId\": 0,
        \"Rank_Stat_Conquest\": 1193.02563,
        \"Rank_Stat_Duel\": 1152.04126,
        \"Rank_Stat_Joust\": 1397.082,
        \"Reference_Name\": \"Nu Wa\",
        \"Region\": \"EU\",
        \"Skin\": \"Old Wa\",
        \"SkinId\": 13320,
        \"Structure_Damage\": 0,
        \"Surrendered\": 0,
        \"TaskForce\": 2,
        \"Team1Score\": 0,
        \"Team2Score\": 0,
        \"TeamId\": 477755,
        \"Team_Name\": \"Last Heroes\",
        \"Time_In_Match_Seconds\": 2014,
        \"Towers_Destroyed\": 0,
        \"Wards_Placed\": 9,
        \"Win_Status\": \"Loser\",
        \"Winning_TaskForce\": 1,
        \"hasReplay\": \"n\",
        \"hz_gamer_tag\": null,
        \"hz_player_name\": \"BAALHAMMUN\",
        \"match_queue_id\": 451,
        \"name\": \"Ranked: Conquest\",
        \"playerId\": \"4353122\",
        \"playerName\": \"[LHero]BAALHAMMUN\",
        \"playerPortalId\": \"1\",
        \"playerPortalUserId\": null,
        \"ret_msg\": null
    }
]";